export default [{
        id: 1,
        name: 'smart-tv1',
        category: 'smart-tv',
        image: "smart-tv1.jpg"
    }, {
        id: 2,
        name: 'headphone1',
        category: 'headphone',
        image: "headphone1.jpg"
    }, {
        id: 3,
        name: 'mobile1',
        category: 'mobile',
        image: "mobile1.jpg"
    }, {
        id: 4,
        name: 'notebook1',
        category: 'notebook',
        image: "notebook1.jpg"
    }, {
        id: 5,
        name: 'watch1',
        category: 'watch',
        image: "watch1.jpg"
    }, {
        id: 6,
        name: 'smart-tv2',
        category: 'smart-tv',
        image: "smart-tv2.jpg"
    }, {
        id: 7,
        name: 'headphone2',
        category: 'headphone',
        image: "headphone2.jpg"
    }, {
        id: 8,
        name: 'mobile2',
        category: 'mobile',
        image: "mobile2.jpg"
    }, {
        id: 9,
        name: 'notebook2',
        category: 'notebook',
        image: "notebook2.jpg"
    }, {
        id: 10,
        name: 'watch2',
        category: 'watch',
        image: "watch2.jpg"
    }, {
        id: 11,
        name: 'smart-tv3',
        category: 'smart-tv',
        image: "smart-tv3.jpg"
    }, {
        id: 12,
        name: 'headphone3',
        category: 'headphone',
        image: "headphone3.jpg"
    }, {
        id: 13,
        name: 'mobile3',
        category: 'mobile',
        image: "mobile3.jpg"
    }, {
        id: 14,
        name: 'notebook3',
        category: 'notebook',
        image: "notebook3.jpg"
    }, {
        id: 15,
        name: 'watch3',
        category: 'watch',
        image: "watch3.jpg"
    }, {
        id: 16,
        name: 'smart-tv4',
        category: 'smart-tv',
        image: "smart-tv4.jpg"
    }, {
        id: 17,
        name: 'headphone4',
        category: 'headphone',
        image: "headphone4.jpg"
    }, {
        id: 18,
        name: 'mobile4',
        category: 'mobile',
        image: "mobile4.jpg"
    }, {
        id: 19,
        name: 'notebook4',
        category: 'notebook',
        image: "notebook4.jpg"
    }, {
        id: 20,
        name: 'watch4',
        category: 'watch',
        image: "watch4.jpg"
    }, {
        id: 21,
        name: 'mobile5',
        category: 'mobile',
        image: "mobile5.jpg"
    },
]